# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.mysql-data:/var/lib/mysql
